// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _374Cloud.Data;

namespace _374Cloud.Migrations
{
    [DbContext(typeof(rst374_cloud12Context))]
    [Migration("20190916225809_myFirst")]
    partial class myFirst
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_374Cloud.Entities.CatalogRef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cat")
                        .IsRequired()
                        .HasColumnName("cat")
                        .HasMaxLength(550);

                    b.Property<int>("ParentId")
                        .HasColumnName("parent_id");

                    b.Property<int?>("Seq")
                        .HasColumnName("seq");

                    b.Property<int>("level");

                    b.HasKey("Id");

                    b.ToTable("catalog_ref");
                });

            modelBuilder.Entity("_374Cloud.Entities.CodeRelations", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("AllocatedStock")
                        .HasColumnName("allocated_stock");

                    b.Property<decimal>("AverageCost")
                        .HasColumnName("average_cost")
                        .HasColumnType("money");

                    b.Property<bool>("AvoidPoint")
                        .HasColumnName("avoid_point");

                    b.Property<string>("Barcode")
                        .HasColumnName("barcode")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("BestBefore")
                        .HasColumnName("best_before")
                        .HasMaxLength(50);

                    b.Property<int?>("BomId")
                        .HasColumnName("bom_id");

                    b.Property<string>("BoxedQty")
                        .HasColumnName("boxed_qty")
                        .HasMaxLength(50);

                    b.Property<string>("Brand")
                        .HasColumnName("brand")
                        .HasMaxLength(50);

                    b.Property<string>("Cat")
                        .HasColumnName("cat")
                        .HasMaxLength(50);

                    b.Property<bool>("Clearance")
                        .HasColumnName("clearance");

                    b.Property<int>("Code")
                        .HasColumnName("code");

                    b.Property<byte?>("ComingSoon")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("coming_soon")
                        .HasDefaultValueSql("((0))");

                    b.Property<double>("CommissionRate")
                        .HasColumnName("commission_rate");

                    b.Property<bool>("CoreRange")
                        .HasColumnName("core_range");

                    b.Property<int?>("CostAccount")
                        .HasColumnName("cost_account");

                    b.Property<int>("CostofsalesAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("costofsales_account")
                        .HasDefaultValueSql("((5111))");

                    b.Property<string>("CountryOfOrigin")
                        .HasColumnName("country_of_origin")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<byte>("Currency")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("currency")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool>("DateRange")
                        .HasColumnName("date_range");

                    b.Property<int>("Disappeared")
                        .HasColumnName("disappeared");

                    b.Property<bool>("DoNotRounddown")
                        .HasColumnName("do_not_rounddown");

                    b.Property<double?>("ExchangeRate")
                        .HasColumnName("exchange_rate");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnName("expire_date")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("ForeignSupplierPrice")
                        .HasColumnName("foreign_supplier_price")
                        .HasColumnType("money");

                    b.Property<bool>("HasScale")
                        .HasColumnName("has_scale");

                    b.Property<bool>("Hidden")
                        .HasColumnName("hidden");

                    b.Property<bool?>("Hot")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("hot")
                        .HasDefaultValueSql("((1))");

                    b.Property<byte?>("Inactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("inactive")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("IncomeAccount")
                        .HasColumnName("income_account");

                    b.Property<int>("InnerPack")
                        .HasColumnName("inner_pack");

                    b.Property<int?>("InventoryAccount")
                        .HasColumnName("inventory_account");

                    b.Property<bool>("IsBarcodeprice")
                        .HasColumnName("is_barcodeprice");

                    b.Property<bool>("IsIdCheck")
                        .HasColumnName("is_id_check");

                    b.Property<bool>("IsMemberOnly")
                        .HasColumnName("is_member_only");

                    b.Property<bool>("IsService")
                        .HasColumnName("is_service");

                    b.Property<bool>("IsSpecial")
                        .HasColumnName("is_special");

                    b.Property<bool>("IsVoidDiscount")
                        .HasColumnName("is_void_discount");

                    b.Property<bool>("IsWebsiteItem")
                        .HasColumnName("is_website_item");

                    b.Property<decimal>("LevelPrice0")
                        .HasColumnName("level_price0")
                        .HasColumnType("money");

                    b.Property<decimal>("LevelPrice1")
                        .HasColumnName("level_price1")
                        .HasColumnType("money");

                    b.Property<decimal>("LevelPrice2")
                        .HasColumnName("level_price2")
                        .HasColumnType("money");

                    b.Property<decimal>("LevelPrice3")
                        .HasColumnName("level_price3")
                        .HasColumnType("money");

                    b.Property<decimal>("LevelPrice4")
                        .HasColumnName("level_price4")
                        .HasColumnType("money");

                    b.Property<decimal>("LevelPrice5")
                        .HasColumnName("level_price5")
                        .HasColumnType("money");

                    b.Property<decimal>("LevelPrice6")
                        .HasColumnName("level_price6")
                        .HasColumnType("money");

                    b.Property<decimal>("LevelPrice7")
                        .HasColumnName("level_price7")
                        .HasColumnType("money");

                    b.Property<decimal>("LevelPrice8")
                        .HasColumnName("level_price8")
                        .HasColumnType("money");

                    b.Property<decimal>("LevelPrice9")
                        .HasColumnName("level_price9")
                        .HasColumnType("money");

                    b.Property<double>("LevelRate1")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("level_rate1")
                        .HasDefaultValueSql("((100))");

                    b.Property<double>("LevelRate2")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("level_rate2")
                        .HasDefaultValueSql("((95))");

                    b.Property<double>("LevelRate3")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("level_rate3")
                        .HasDefaultValueSql("((90))");

                    b.Property<double>("LevelRate4")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("level_rate4")
                        .HasDefaultValueSql("((85))");

                    b.Property<double>("LevelRate5")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("level_rate5")
                        .HasDefaultValueSql("((80))");

                    b.Property<double>("LevelRate6")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("level_rate6")
                        .HasDefaultValueSql("((78))");

                    b.Property<double?>("LevelRate7")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("level_rate7")
                        .HasDefaultValueSql("((75))");

                    b.Property<double?>("LevelRate8")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("level_rate8")
                        .HasDefaultValueSql("((73))");

                    b.Property<double?>("LevelRate9")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("level_rate9")
                        .HasDefaultValueSql("((70))");

                    b.Property<int>("Line1Font")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("line1_font")
                        .HasDefaultValueSql("((9))");

                    b.Property<int>("Line2Font")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("line2_font")
                        .HasDefaultValueSql("((9))");

                    b.Property<int>("LowStock")
                        .HasColumnName("low_stock");

                    b.Property<decimal>("ManualCostFrd")
                        .HasColumnName("manual_cost_frd")
                        .HasColumnType("money");

                    b.Property<decimal>("ManualCostNzd")
                        .HasColumnName("manual_cost_nzd")
                        .HasColumnType("money");

                    b.Property<double>("ManualExchangeRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("manual_exchange_rate")
                        .HasDefaultValueSql("((1))");

                    b.Property<int?>("Moq")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("moq")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(255);

                    b.Property<string>("NameCn")
                        .HasColumnName("name_cn")
                        .HasMaxLength(350);

                    b.Property<bool>("NewItem")
                        .HasColumnName("new_item");

                    b.Property<DateTime?>("NewItemDate")
                        .HasColumnName("new_item_date")
                        .HasColumnType("datetime");

                    b.Property<bool>("NoDiscount")
                        .HasColumnName("no_discount");

                    b.Property<double?>("NormalPrice")
                        .HasColumnName("normal_price");

                    b.Property<decimal>("NzdFreight")
                        .HasColumnName("nzd_freight")
                        .HasColumnType("money");

                    b.Property<string>("OuterPackBarcode")
                        .HasColumnName("outer_pack_barcode")
                        .HasMaxLength(99)
                        .IsUnicode(false);

                    b.Property<string>("PackageBarcode1")
                        .HasColumnName("package_barcode1")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("PackageBarcode2")
                        .HasColumnName("package_barcode2")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("PackageBarcode3")
                        .HasColumnName("package_barcode3")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<double?>("PackagePrice1")
                        .HasColumnName("package_price1");

                    b.Property<double?>("PackagePrice2")
                        .HasColumnName("package_price2");

                    b.Property<double?>("PackagePrice3")
                        .HasColumnName("package_price3");

                    b.Property<int?>("PackageQty1")
                        .HasColumnName("package_qty1");

                    b.Property<int?>("PackageQty2")
                        .HasColumnName("package_qty2");

                    b.Property<int?>("PackageQty3")
                        .HasColumnName("package_qty3");

                    b.Property<bool>("PickDate")
                        .HasColumnName("pick_date");

                    b.Property<bool?>("Popular")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("popular")
                        .HasDefaultValueSql("((1))");

                    b.Property<decimal>("Price1")
                        .HasColumnName("price1")
                        .HasColumnType("money");

                    b.Property<decimal>("Price2")
                        .HasColumnName("price2")
                        .HasColumnType("money");

                    b.Property<decimal>("Price3")
                        .HasColumnName("price3")
                        .HasColumnType("money");

                    b.Property<decimal>("Price4")
                        .HasColumnName("price4")
                        .HasColumnType("money");

                    b.Property<decimal>("Price5")
                        .HasColumnName("price5")
                        .HasColumnType("money");

                    b.Property<decimal>("Price6")
                        .HasColumnName("price6")
                        .HasColumnType("money");

                    b.Property<decimal>("Price7")
                        .HasColumnName("price7")
                        .HasColumnType("money");

                    b.Property<decimal>("Price8")
                        .HasColumnName("price8")
                        .HasColumnType("money");

                    b.Property<decimal>("Price9")
                        .HasColumnName("price9")
                        .HasColumnType("money");

                    b.Property<decimal>("PriceSystem")
                        .HasColumnName("price_system")
                        .HasColumnType("money");

                    b.Property<int?>("PrintFormatCode")
                        .HasColumnName("print_format_code");

                    b.Property<string>("ProductCode")
                        .HasColumnName("product_code")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("PromoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("promo_id")
                        .HasDefaultValueSql("((0))");

                    b.Property<byte?>("Promotion")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("promotion")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("QposQtyBreak")
                        .HasColumnName("qpos_qty_break");

                    b.Property<int>("QtyBreak1")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("qty_break1")
                        .HasDefaultValueSql("((5))");

                    b.Property<int?>("QtyBreak2")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("qty_break2")
                        .HasDefaultValueSql("((10))");

                    b.Property<int?>("QtyBreak3")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("qty_break3")
                        .HasDefaultValueSql("((20))");

                    b.Property<int?>("QtyBreak4")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("qty_break4")
                        .HasDefaultValueSql("((50))");

                    b.Property<int?>("QtyBreak5")
                        .HasColumnName("qty_break5");

                    b.Property<int?>("QtyBreak6")
                        .HasColumnName("qty_break6");

                    b.Property<int?>("QtyBreak7")
                        .HasColumnName("qty_break7");

                    b.Property<int?>("QtyBreak8")
                        .HasColumnName("qty_break8");

                    b.Property<int?>("QtyBreak9")
                        .HasColumnName("qty_break9");

                    b.Property<double>("QtyBreakDiscount1")
                        .HasColumnName("qty_break_discount1");

                    b.Property<double?>("QtyBreakDiscount2")
                        .HasColumnName("qty_break_discount2");

                    b.Property<double?>("QtyBreakDiscount3")
                        .HasColumnName("qty_break_discount3");

                    b.Property<double?>("QtyBreakDiscount4")
                        .HasColumnName("qty_break_discount4");

                    b.Property<double?>("QtyBreakDiscount5")
                        .HasColumnName("qty_break_discount5");

                    b.Property<double?>("QtyBreakDiscount6")
                        .HasColumnName("qty_break_discount6");

                    b.Property<double?>("QtyBreakDiscount7")
                        .HasColumnName("qty_break_discount7");

                    b.Property<double?>("QtyBreakDiscount8")
                        .HasColumnName("qty_break_discount8");

                    b.Property<double?>("QtyBreakDiscount9")
                        .HasColumnName("qty_break_discount9");

                    b.Property<decimal?>("QtyBreakPrice1")
                        .HasColumnName("qty_break_price1")
                        .HasColumnType("money");

                    b.Property<decimal?>("QtyBreakPrice10")
                        .HasColumnName("qty_break_price10")
                        .HasColumnType("money");

                    b.Property<decimal?>("QtyBreakPrice2")
                        .HasColumnName("qty_break_price2")
                        .HasColumnType("money");

                    b.Property<decimal?>("QtyBreakPrice3")
                        .HasColumnName("qty_break_price3")
                        .HasColumnType("money");

                    b.Property<decimal?>("QtyBreakPrice4")
                        .HasColumnName("qty_break_price4")
                        .HasColumnType("money");

                    b.Property<decimal?>("QtyBreakPrice5")
                        .HasColumnName("qty_break_price5")
                        .HasColumnType("money");

                    b.Property<decimal?>("QtyBreakPrice6")
                        .HasColumnName("qty_break_price6")
                        .HasColumnType("money");

                    b.Property<decimal?>("QtyBreakPrice7")
                        .HasColumnName("qty_break_price7")
                        .HasColumnType("money");

                    b.Property<decimal?>("QtyBreakPrice8")
                        .HasColumnName("qty_break_price8")
                        .HasColumnType("money");

                    b.Property<decimal?>("QtyBreakPrice9")
                        .HasColumnName("qty_break_price9")
                        .HasColumnType("money");

                    b.Property<double>("Rate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("rate")
                        .HasDefaultValueSql("((1.1))");

                    b.Property<bool>("RealStock")
                        .HasColumnName("real_stock");

                    b.Property<int>("RedeemPoint")
                        .HasColumnName("redeem_point");

                    b.Property<string>("RefCode")
                        .HasColumnName("ref_code")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<decimal>("Rrp")
                        .HasColumnName("rrp")
                        .HasColumnType("money");

                    b.Property<string>("SCat")
                        .HasColumnName("s_cat")
                        .HasMaxLength(50);

                    b.Property<string>("ScaleDescriptionLine1")
                        .HasColumnName("scale_description_line1")
                        .HasMaxLength(50);

                    b.Property<string>("ScaleDescriptionLine2")
                        .HasColumnName("scale_description_line2")
                        .HasMaxLength(50);

                    b.Property<string>("SellBy")
                        .HasColumnName("sell_by")
                        .HasMaxLength(50);

                    b.Property<bool>("Skip")
                        .HasColumnName("skip");

                    b.Property<string>("SkuCode")
                        .HasColumnName("sku_code")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<decimal?>("SpecialCost")
                        .HasColumnName("special_cost")
                        .HasColumnType("money");

                    b.Property<DateTime?>("SpecialCostEndDate")
                        .HasColumnName("special_cost_end_date")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("SpecialCostStartDate")
                        .HasColumnName("special_cost_start_date")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("SpecialPrice")
                        .HasColumnName("special_price")
                        .HasColumnType("money");

                    b.Property<DateTime?>("SpecialPriceEndDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("special_price_end_date")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("SpecialPriceStartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("special_price_start_date")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SsCat")
                        .HasColumnName("ss_cat")
                        .HasMaxLength(50);

                    b.Property<string>("StockLocation")
                        .HasColumnName("stock_location")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Supplier")
                        .HasColumnName("supplier")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("SupplierCode")
                        .HasColumnName("supplier_code")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal?>("SupplierPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("supplier_price")
                        .HasColumnType("money")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("Tareweight")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tareweight")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("TaxCode")
                        .HasColumnName("tax_code")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<double>("TaxRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tax_rate")
                        .HasDefaultValueSql("((0.15))");

                    b.Property<int>("Unit")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("unit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("UsedBy")
                        .HasColumnName("used_by")
                        .HasMaxLength(50);

                    b.Property<double?>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("weight")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.HasIndex("Cat")
                        .HasName("IDX_code_relations_cat");

                    b.HasIndex("Clearance")
                        .HasName("IDX_code_relations_clearance");

                    b.HasIndex("Code")
                        .HasName("IDX_code_relations_code");

                    b.HasIndex("Id")
                        .HasName("IDX_code_relations_id");

                    b.HasIndex("SCat")
                        .HasName("IDX_code_relations_scat");

                    b.HasIndex("SsCat")
                        .HasName("IDX_code_relations_sscat");

                    b.HasIndex("SupplierCode")
                        .HasName("IDX_code_relations_spl_code");

                    b.ToTable("code_relations");
                });
#pragma warning restore 612, 618
        }
    }
}
